name: gestion_stock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  crypto: ^3.0.0
  camera: ^0.9.3+1
  barcode: ^2.2.4
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  provider: ^6.1.2
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/zero-two-bot.jpg
