// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAAzSy9dBPM76yySvmST-MXOMZqLdmpps',
    appId: '1:163125879536:web:8c796b77eb9304710d5835',
    messagingSenderId: '163125879536',
    projectId: 'gestionstocks-98ab5',
    authDomain: 'gestionstocks-98ab5.firebaseapp.com',
    databaseURL: 'https://gestionstocks-98ab5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionstocks-98ab5.appspot.com',
    measurementId: 'G-QRXQVTVKVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_fJVtPrtysQY-IjhMfzlq5IxzTDvHBBQ',
    appId: '1:163125879536:android:add4df57168b35950d5835',
    messagingSenderId: '163125879536',
    projectId: 'gestionstocks-98ab5',
    databaseURL: 'https://gestionstocks-98ab5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionstocks-98ab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbGDvfVQ-2iNdn2M44krk5u_8jPLpxa2I',
    appId: '1:163125879536:ios:7b39ae8cd894d20e0d5835',
    messagingSenderId: '163125879536',
    projectId: 'gestionstocks-98ab5',
    databaseURL: 'https://gestionstocks-98ab5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionstocks-98ab5.appspot.com',
    iosBundleId: 'com.example.gestionStock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbGDvfVQ-2iNdn2M44krk5u_8jPLpxa2I',
    appId: '1:163125879536:ios:7b39ae8cd894d20e0d5835',
    messagingSenderId: '163125879536',
    projectId: 'gestionstocks-98ab5',
    databaseURL: 'https://gestionstocks-98ab5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionstocks-98ab5.appspot.com',
    iosBundleId: 'com.example.gestionStock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAAzSy9dBPM76yySvmST-MXOMZqLdmpps',
    appId: '1:163125879536:web:30efcbf6eee631850d5835',
    messagingSenderId: '163125879536',
    projectId: 'gestionstocks-98ab5',
    authDomain: 'gestionstocks-98ab5.firebaseapp.com',
    databaseURL: 'https://gestionstocks-98ab5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionstocks-98ab5.appspot.com',
    measurementId: 'G-B6HNYQ6G70',
  );
}
